def replay_error_trace(verifier_output):
    print "TODO: replay the erorr trace"
